config/routes.rb
Timebank::Application.routes.draw do

 
  resources :comments

  resources :candidates do
    member do
      post :confirm
      post :confirm_cand
      post :cancel
    end
    resources :comments
  end
  
  resources :jobs do
    collection do
      get :ajax
    end
    member do
      post :done
    end
    resources :candidates 
    resources :comments
  end
 

  
  devise_for :users
  

  

  root :to => 'jobs#index'
 

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
  has_many :comments, :as => :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
def before_save
  self.bill = 1
end
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  validates :body, :presence => true 
  scope :public, where(:public => true)
  scope :private, where(:public => false)
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many :candidates
  has_many :comments, :as => :commentable
  belongs_to :worker, :class_name=>"Candidate", :foreign_key => :worker_id
  validates :cost, :name, :presence => :true
  validates :description, :length => {:in => 10..950}
  validates :status, :inclusion => { :in => ["free", "in process", "finished"]}
  
end

app/models/user.rb
class User < ActiveRecord::Base 
  before_save do |user|
    user.bill = 1
  end
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :jobs
  has_many :comments
  has_many :candidates
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Job.find(params[:job_id]).candidates
  end

  def show
    @candidate = Candidate.find(params[:id])
    @job = Job.find(params[:job_id])
    @comment = @job.comments.new params[:comment]
  end

  def new
    @job = Job.find(params[:job_id])
    @candidate = @job.candidates.new
    
    
  end

  def create
    
    @job = Job.find(params[:job_id])
    @candidate = @job.candidates.new
    @candidate.user_id = current_user.id
    if @candidate.save
      flash[:notice] = 'Candidate created'
      redirect_to job_candidate_url(@job, @candidate)
    else
      render :new
    end
    
  end

  def edit
    @candidate = Candidate.find(params[:id])
  end

  def update
    @candidate = Candidate.find(params[:id])
    if @candidate.update_attributes(params[:candidates])
      flash[:notice] = 'Candidate updated'
      redirect_to @candidate
    else
      render :edit
    end
  end
  

  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy
    redirect_to Candidate
  end
  


  def confirm
    @candidate = Candidate.find params[:id]
    @job = @candidate.job
    @user_owner = @job.user
    if (@user_owner.bill >= @job.cost)
    @job.check_status_owner = true;
    @job.worker_id = @candidate.id
    @job.save
    @comment = @job.comments.new params[:comment]
    render :show
    else
      flash.now[:notice] = 'Your balance is not enough to pay'
      @comment = @job.comments.new params[:comment]
      render :show
    end
  end

  def confirm_cand
    @candidate = Candidate.find params[:id]
    @job = @candidate.job
    @job.check_status_worker = true;
    @job.status = "in process"
    @job.save
    @comment = @job.comments.new params[:comment]
    render :show
   end
  
  def cancel
    @candidate = Candidate.find params[:id]
    @job = @candidate.job
    @job.check_status_owner = false;
    @job.check_status_worker = false
    @job.worker_id = nil
    @job.status = "free"
    @job.save
    @comment = @job.comments.new params[:comment]
    render :show
  end
  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  def index
    if params[:job_id].present?
      @job = Job.find(params[:job_id])
      @comments = @job.comments
       @comment = @job.comments.new
    elsif params[:candidate_id].present?
      @candidate = Candidate.find(params[:candidate_id])
      @comments = @candidate.comments
       @comment = @candidate.comments.new
    end
    
    user_id = params[:user_id]
    if !user_id
      user_id = current_user.id
    end
    @user = User.find(user_id)
  end

  def show
    @comment = Comment.find params[:id]
  end

  def new
    @comment = Comment.new
  end

  def create
    if (params[:job_id])
      @job = Job.find(params[:job_id])
      @comment = @job.comments.new params[:comment]
    else  
      @candidate = Candidate.find(params[:candidate_id])
      @job = @candidate.job
      @comment = @candidate.comments.new params[:comment]
    end
    @comment.user = current_user
    if params[:public_comment]
      @comment.public = true
    else @comment.public = false
    end
    if @comment.save
      if (params[:job_id])
        flash[:notice] = 'Comment created'
        redirect_to @job
      else
        flash[:notice] = 'Comment created'
        redirect_to job_candidate_path(@job.id, @candidate.id)
        
      end
      
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find params[:id]
        
  end

  def destroy
    @comment = Comment.find params[:id]
    @job = @comment.job
    @comment.destroy
    redirect_to  @job   
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index,:show]
  def index
    @jobs = Job.all
    
  end

  def show
   
      @job = Job.find params[:id]
      @comment = Comment.new
      @candidate = Candidate.find_by_user_id_and_job_id(current_user.id,@job.id)
  
    end

    def new
      @job = Job.new
    end

    def create
      @job = current_user.jobs.new params[:job]
      if @job.save
        flash[:notice] = 'Job created'
        redirect_to @job
      else
        render :new 
      end 
    end

    def edit 
      if (current_user.id == @job.user_id)
        @job = Job.find params[:id]
      else
        flash[:notice] = 'You are not owner!'
      end
    end

    def update
      @job = Job.find params[:id]
      if @job.update_attributes(params[:job])
        flash[:notice] = 'Job updated'
        redirect_to @job
      else
        render :edit
      end
    end

    def destroy
      @job = Job.find params[:id]
      if (current_user.id == @job.user_id)
        @job.destroy
        redirect_to @job
      else
        flash.now[:notice] = 'You are not owner!'
        render :show
      end
    end

 
  def ajax
    render :text => "Thanks"
  end


  def done
    @job = Job.find params[:id]
    @candidate = @job.worker
    @user_owner = @job.user
    @user_worker = @candidate.user
    @user_owner.bill -= @job.cost
    @user_worker.bill += @job.cost
    @job.status = "finished"
    @job.save
    @user_worker.save
    @user_owner.save
    redirect_to jobs_path
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/candidates/_form.html.erb
<%= form_for [@job] do |f|%>

  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% @candidate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <%end%>

  



<%end%>

app/views/candidates/edit.html.erb
<h1>Candidates#edit</h1>
<p>Find me in app/views/candidates/edit.html.erb</p>

app/views/candidates/index.html.erb
<h1>Candidates#index</h1>
<%=@user.email%>

<br/>
Історія переписки

app/views/candidates/new.html.erb
<h1>Candidates#new</h1>
<p>Find me in app/views/candidates/new.html.erb</p>

app/views/candidates/show.html.erb
<h1>Candidates#show</h1>
<h2><%=link_to @job.name, job_path(@job) %></h2>
<table border="1" cellpadding="5">

  <tr><td> <%=@job.description%></td></tr>

  <tr><td><%=@job.cost%></td></tr>
  <tr><td><%=@job.created_at%></td></tr>
  <tr><td><%=@job.status%></td>

</table>

<%if @job.user_id == current_user.id && @job.worker_id == nil%>
  <%=link_to "Confirm", confirm_candidate_path(@candidate), :method => :post%>
<%end%>
<%if @job.worker_id == @candidate.id && @candidate.user_id == current_user.id && @job.check_status_worker == false%>
  <%=link_to "Confirm", confirm_cand_candidate_path(@candidate), :method => :post%>
<%end%>
<%if @job.user_id == current_user.id && @job.worker_id != nil && @job.check_status_worker == false%>
  <%=link_to "Cancel", cancel_candidate_path(@candidate), :method => :post%>
<%end%>

</br>
Історія переписки

<% @candidate.comments.each do |comment|%>
  <div class="comment">
    <b><%=comment.user.email%></b>
    <small><%=comment.created_at%></small>
    <br/>
    <%=simple_format truncate(comment.body)%>
  </div>
<%end%>



<%=render 'candidates/form'%>
<%=render 'comments/form_for_candidate'%>

app/views/comments/_form_for_candidate.erb
<%= form_for @comment, :url => candidate_comments_path(@candidate.id) do |f|  %>
  <div class="field">
    <%= f.text_area :body, :size => '40x5' %>
  </div>

  <%=f.hidden_field :user_id%>

  <div class="actions">
    <%= f.submit "Add private comment", :name => 'private_comment'%>
  </div>
  
  
<% end %>

app/views/comments/_form_for_job.html.erb
<%= form_for @comment, :url => job_comments_path(@job.id) do |f|  %>
  <div class="field">
    <%= f.text_area :body, :size => '40x5' %>
  </div>

  <%=f.hidden_field :user_id%>

  <div class="actions">
    <%= f.submit "Add comment", :name => 'public_comment'%>
  </div>
  
  
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
<% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      
      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div>
<div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status%>
  </div>
<div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost%>
  </div>
<div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

<div class="actions">
    <%= f.submit %>
  </div>



<% end %>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>

<%=render "form"%>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', job_path %>

app/views/jobs/index.html.erb
<table border="1">
  <tr>
    <th>Назва роботи</th>

    <th>Опис роботи</th>
    <th>Ціна</th>
    <th>Час створення</th>
    <th>Статус</th>
    <th>Роботодавець</th>

  </tr>

  <% @jobs.each do |job| %>
    <tr>


      <td><%if current_user%>

          <%=link_to job.name, job_path(job)%>
        <%else%>
          <%=link_to job.name, new_user_session_path%></td>
        </td>
      <%end%>
      <td> <%=simple_format truncate(job.description, :length=>2000, :separator=>" ", :omission => "... (#{link_to 'більше тексту', job_path(job)})")%></td>

      <td><%=job.cost%></td>
      <td><%=job.created_at%></td>
      <td><%=job.status%></td>
      <td><%=job.user.email%></td>

    </tr>

  <%end%>


</table>  
<%=link_to "Ап-Чхи", ajax_jobs_path, :remote =>true, :class =>"ajax_link"%>

app/views/jobs/new.html.erb
<%=render "form"%>

app/views/jobs/show.html.erb
<%=link_to "Будь здоров", ajax_jobs_path, :remote => true, :class => "ajax_link"%>


<h1>Jobs#show</h1>

<h2><%= @job.name %></h2>
<table border="1" cellpadding="5">
  <tr>
  <tr><td>Опис</td>  <td> <%=@job.description%></td></tr>
  <tr><td>Ціна</td>
    <td><%=@job.cost%></td></tr>
  <tr><td>Створено</td>
    <td><%=@job.created_at%></td></tr>
  <tr><td>Статус</td>
    <td><%=@job.status%></td>

  <tr><td>Створив</td>
    <td><%=@job.user.email%></td> 
    <%if (current_user.id == @job.user_id)%>

    <tr><td>Кандидати</td>
      <td><%@job.candidates.each do |candidate|%>
          <%=link_to candidate.user.email, job_candidate_path(@job, candidate.id)%>
        <%end%>    
      <%end%>
    </td></tr>


  <tr><td>Можливості</td>
    <%if (current_user.id == @job.user_id)%>
      <td><%= link_to 'Edit', edit_job_path(@job) %> |
        <%= link_to 'Destroy', @job, confirm: 'Are you sure?', method: :delete %>


      <%else%> <%if (@job.candidates.where(:user_id => current_user.id).count > 0)  %>
        <td> <%=link_to 'Go to private', job_candidate_path(@job.id, @candidate)%></td>
      <%else%> 
        <td> <%=link_to 'Apply', job_candidates_path(@job), :method => :post%> </td>
      <%end%>



    <%end%>
 
  <%if @job.user_id == current_user.id && @job.status == "in process" %>
    <%=link_to "Job is done", done_job_path(@candidate), :method => :post%>
  <%end%>

    </td>
  </tr>
</table>


<h3>Коментарі</h3>
<% @job.comments.public.each do |comment|%>
<div class="comment">
  <b><%=comment.user.email%></b>
  <small><%=comment.created_at%></small>
  <br/>
  <%=simple_format truncate(comment.body)%>
</div>
<%end%>







<h3>Додати коментар</h3>


<%=render 'comments/form_for_job'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head


    <title>Timebank</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="site">
      <div class="header"><h1>Timebank</h1>


        <b><%=current_user.email if current_user%></b>

        <%if current_user && current_user.bill != nil%> <%=', Your balance is' %> <%=current_user.bill %>
        <%end%>



      </div>
      <div class="main">

        <div class="main_menu">
          <div class="content-wrapper">
            <b> <%= link_to "All jobs", jobs_path%>  </b>
            |               
            <b><%= link_to "Add job", new_job_path%> </b>

            ]          
           
            <b> <%=link_to "Sign out", destroy_user_session_path, :method => :delete if current_user%></b>
            |  
            <b><%=link_to "Sign in", new_user_session_path if !current_user%></b>
            |
            <b><%=link_to "Registry", new_user_registration_path if !current_user%></b>
            |          
            

            <t/>


           
          </div> 
        </div>
      </div>

      <div class="notice">
        <%=notice%>
      </div>
      <div class="content">
        <div class="content-wrapper"><%= yield %></div>
      </div>
      <div class="footer">&copy; Time Bank 2011</div>
    </div>


  </body>
</html>